### ISSUE TITLE
options in usamp_opts/osamp_opts do not work

### ISSUE THREAD

**Issue by Seamanan** [s-kganz/scutr#3]
The options for SCUT do not work.
Error in dist(data[, -which(names(data) == cls_col)], ...) :
unused argument (k = 7)

I run and that is the error.
library(scutr)
data(imbalance)
imbalance <- imbalance[imbalance$class %in% c(2, 3, 19, 20), ]
imbalance$class <- as.numeric(imbalance$class)

plot(imbalance$V1, imbalance$V2, col=imbalance$class)

scutted <- SCUT(imbalance, "class", undersample = undersample_kmeans,
usamp_opts = list(k=7))

It also does not work in a specific data set i am working on. I have problems with the options in general.
Could you explain me if there is a problem in the function or something wrong from my side?

**Comment by s-kganz** [comment]
Hi @Seamanan,

I just ran the example you provided above with `imbalance` and k set to 7 and did not get an error. Could you provide a different example so that I can reproduce and try to solve your issue?

**Comment by Seamanan** [comment]
I solved, sorry for the question s-kganz.
I apologize for the late reply.
